[project]
name = "styx"
version = "0.1.0"
description = "A quantum circuit simulator based on Tensor Networks"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.3.5",
    "scipy>=1.16.3",
]
